name = "vueblog"
compatibility_date = "2024-11-28"

# Specify the entry point for the Worker script
main = "src/index.ts"  # 根据实际情况调整路径

[build]
  command = "npm run build"

[[assets]]
directory = "./dist"  # 如果您有构建后的静态文件
